### PR TITLE
Feature/google poly

### PR DESCRIPTION
**Pull request by bnolan**
Keen for a review, but it needs a bit of UI work before we can merge it to master. I'm not sure where the google poly sidebar should display, on the left, on the right? In place or at the same time as the inspector? Maybe as a component under the inspector? I'm not sure - thoughts?

### CODE REVIEW

**Comment by eordano** [comment]
needs rebase?

**Comment by carlfravel** [comment]
I haven't seen it yet, but my uninformed intuition says if it is about adding a component, then to the left. If about editing it's properties then to the right.
Is it visible where I could see it somewhere yet?

**Comment by bnolan** [comment]
Hey @carlfravel we need to set up feature branch to subdomain deployment before you can see how this works. It currently displays on the right in addition to the inspector, so it takes up way too much screen space. I'll try rebase it and get it displaying on the left hand side under a tab 'add poly' and post a screenshot.

**Review by eordano — CHANGES_REQUESTED** [review]
Please use the new API and try to avoid a proxy server

**Pull request merged**
